[files]
"/scripts/api.py" = "./api.py"
"/scripts/api_implementation.py" = "./api_implementation.py"
"/scripts/constants.py" = "./constants.py"
"/scripts/game_config.py" = "./game_config.py"
"/scripts/game_state.py" = "./game_state.py"
"/scripts/game_renderer.py" = "./game_renderer.py"
"/scripts/game_simulator.py" = "./game_simulator.py"
"/scripts/code_battles/__init__.py" = "./code_battles/__init__.py"
"/scripts/code_battles/utilities.py" = "./code_battles/utilities.py"
